
sudo: required
language: node_js

services:
  - docker

before_script:
  - chmod +x .docker/scripts/install_hugo.sh
  - chmod +x .docker/scripts/build.sh
  - chmod ugo+x .docker/scripts/deploy.sh
  - npm i -g surge

script:
  - docker build -t poc-hugo -f Dockerfile .
  - docker ps -a
  - docker run poc-hugo
