
sudo: required
language: node_js

services:
  - docker

before_script:
  - chmod +x .docker/scripts/install_hugo.sh
  - chmod +x .docker/scripts/build.sh
  - chmod +x .docker/scripts/deploy.sh
  - chmod +x .docker/scripts/set_env.sh
  - echo ${TRAVIS_REPO_SLUG}

script:
  - docker build -t poc-hugo -f Dockerfile .
  - docker ps -a
  - docker run poc-hugo
