
sudo: required
language: go

services:
  - docker

before_script:
  - chmod +x .docker/scripts/install_hugo.sh
  - chmod +x .docker/scripts/build.sh

script:
  - docker build -t poc-hugo -f Dockerfile .
  - docker ps -a
  - docker run poc-hugo
